# Generated by Django 2.0.5 on 2018-06-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='bladefault', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
