# Generated by Django 2.0.5 on 2018-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='balance_before',
        ),
        migrations.AddField(
            model_name='purchase',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
