# Generated by Django 2.0.5 on 2018-06-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ManyToManyField(related_name='items', to='products.Product'),
        ),
    ]
