# Generated by Django 2.0.5 on 2018-06-27 13:25

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
