# Generated by Django 2.0.8 on 2018-10-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180924_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileattachment',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='files',
            field=models.ManyToManyField(blank=True, to='products.FileAttachment'),
        ),
    ]
