# Generated by Django 2.0.8 on 2018-09-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180907_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='item',
            name='requests',
            field=models.ManyToManyField(blank=True, editable=False, related_name='item_requests', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ItemType', verbose_name='Typ'),
        ),
    ]
