# Generated by Django 2.0.7 on 2018-08-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180804_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
