# Generated by Django 2.0.8 on 2018-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_itemtype_limited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='accessible',
            new_name='accessible_at',
        ),
        migrations.RenameField(
            model_name='itemtype',
            old_name='purchasable',
            new_name='purchasable_at',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='buy_together',
            field=models.ManyToManyField(related_name='_itemtype_buy_together_+', to='products.ItemType'),
        ),
    ]
