# Generated by Django 2.0.8 on 2018-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180919_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='buy_together',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='contains',
            field=models.ManyToManyField(related_name='contained_in', to='products.ItemType'),
        ),
    ]
