# Generated by Django 2.0.8 on 2018-10-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='buy_once',
            field=models.BooleanField(default=False),
        ),
    ]
