# Generated by Django 2.0.7 on 2018-08-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180823_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='requests',
            field=models.ManyToManyField(related_name='item_requests', to='users.Profile'),
        ),
    ]
