# Generated by Django 2.0.9 on 2018-11-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_item_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='expires',
            new_name='_expires',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='expires_on_product_date',
            field=models.BooleanField(default=False),
        ),
    ]
