# Generated by Django 2.0.8 on 2018-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180826_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='requestable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='unavailability_notice',
            field=models.CharField(default='Nicht verfügbar', max_length=20),
        ),
    ]
