# Generated by Django 2.0.9 on 2018-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181101_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='additional_supply',
            field=models.BooleanField(default=False),
        ),
    ]
