# Generated by Django 2.0.8 on 2018-09-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180901_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
    ]
