# Generated by Django 2.0.8 on 2018-09-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_item_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
    ]
