# Generated by Django 2.0.8 on 2018-09-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180904_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='accessable',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='purchaseable',
            field=models.SmallIntegerField(default=0),
        ),
    ]
