# Generated by Django 2.0.9 on 2018-11-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181125_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='_amount',
            new_name='amount',
        ),
    ]
