# Generated by Django 2.0.8 on 2018-09-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180905_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='accessable',
            new_name='accessible',
        ),
        migrations.RenameField(
            model_name='itemtype',
            old_name='purchaseable',
            new_name='purchasable',
        ),
    ]
