# Generated by Django 2.0.9 on 2018-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_itemtype_inform_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='already_uploaded_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
