# Generated by Django 2.0.9 on 2018-12-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181210_2233'),
        ('products', '0015_fileattachment_already_uploaded_url'),
    ]

    operations = [
    ]
