# Generated by Django 2.0.9 on 2018-12-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_merge_20181218_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
