# Generated by Django 2.1.7 on 2019-03-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181218_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['product', '_price'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='itemtype',
            name='requires_donation',
            field=models.BooleanField(default=True),
        ),
    ]
