# Generated by Django 2.1.7 on 2019-03-31 09:45

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import products.behaviours


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20181119_1707'),
        ('users', '0007_auto_20181217_1412'),
        ('products', '0019_auto_20190329_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(blank=True)),
                ('amount', models.SmallIntegerField()),
                ('slug', models.SlugField(default=products.behaviours.PayAble._get_default_id, max_length=100, unique=True)),
                ('executed', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
                ('approval_url', models.CharField(blank=True, max_length=200)),
                ('payment_id', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.PaymentMethod')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
