# Generated by Django 2.1.7 on 2019-03-31 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='item',
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Purchase'),
        ),
    ]
