# Generated by Django 2.1.7 on 2019-04-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190403_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='show_remaining_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
