# Generated by Django 2.1.7 on 2019-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_itemtype_show_remaining_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('included_in', models.ManyToManyField(to='products.ItemType')),
            ],
        ),
    ]
