# Generated by Django 2.0.5 on 2018-07-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('levels', models.ManyToManyField(to='donations.DonationLevel')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Menu')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuSubItem',
            fields=[
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('levels', models.ManyToManyField(to='donations.DonationLevel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='framework.MenuItem')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
