# Generated by Django 2.0.5 on 2018-07-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('framework', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='levels',
            field=models.ManyToManyField(to='users.Donation'),
        ),
    ]
