# Generated by Django 2.0.5 on 2018-07-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20180714_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menusubitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
