# Generated by Django 2.0.5 on 2018-07-19 17:55

from django.db import migrations


def create_menues(apps, schema_editor):
    Menu = apps.get_model('framework', 'Menu')
    Menu.objects.update_or_create(title='main')


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20180719_1954'),
    ]

    operations = [
        migrations.RunPython(create_menues)
    ]
