# Generated by Django 2.0.5 on 2018-07-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_paymentmethod_local_approval'),
        ('framework', '0003_auto_20180719_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='menusubitem',
            options={'ordering': ['ordering']},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='target',
        ),
        migrations.RemoveField(
            model_name='menusubitem',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='menusubitem',
            name='target',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='max_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menuitem_max', to='donations.DonationLevel', verbose_name='Sichtbar bis'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='min_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menuitem_min', to='donations.DonationLevel', verbose_name='Sichtbar ab'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(default='users:profile', max_length=50, verbose_name='URL Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menusubitem',
            name='url_name',
            field=models.CharField(default='users:profile', max_length=50, verbose_name='URL Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ordering',
            field=models.SmallIntegerField(verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='menusubitem',
            name='ordering',
            field=models.SmallIntegerField(verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='menusubitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
