# Generated by Django 2.0.5 on 2018-07-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_auto_20180720_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='max_level',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='min_level',
        ),
        migrations.RemoveField(
            model_name='menusubitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='MenuSubItem',
        ),
    ]
