# Generated by Django 2.0.8 on 2018-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_pk',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
