# Generated by Django 2.0.8 on 2018-09-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180917_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name='Straße'),
        ),
    ]
