# Generated by Django 2.0.9 on 2018-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_old_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uninsterested',
            field=models.BooleanField(default=False),
        ),
    ]
