# Generated by Django 2.0.5 on 2018-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180702_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationlevel',
            name='amount',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
