# Generated by Django 2.0.8 on 2018-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180917_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefonnummer'),
        ),
    ]
