# Generated by Django 2.0.9 on 2018-11-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_uninsterested'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='old_pk',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
