# Generated by Django 2.0.8 on 2018-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180917_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pk_old',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
