# Generated by Django 2.0.9 on 2018-12-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181125_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uninsterested',
            new_name='uninterested',
        ),
    ]
