# Generated by Django 2.0.8 on 2018-09-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_pk_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pk_old',
        ),
    ]
