# Generated by Django 2.0.8 on 2018-09-24 11:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import donations.behaviours
import donations.models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(blank=True)),
                ('slug', models.SlugField(default=products.behaviours.PayAble._get_default_id, max_length=100, unique=True)),
                ('executed', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
                ('approval_url', models.CharField(blank=True, max_length=200)),
                ('payment_id', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.SmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('expiration', models.DateField(default=donations.models.Donation._default_expiration)),
            ],
            options={
                'verbose_name': 'Unterstützung',
                'verbose_name_plural': 'Unterstuetzungen',
            },
        ),
        migrations.CreateModel(
            name='DonationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('amount', models.SmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Spendenstufe',
                'verbose_name_plural': 'Spendenstufen',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField()),
                ('local_approval', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Zahlungsmethode',
                'verbose_name_plural': 'Zahlungsmethoden',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.PaymentMethod'),
        ),
    ]
