# Generated by Django 2.0.7 on 2018-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(),
        ),
    ]
