# Generated by Django 2.0.8 on 2018-10-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationlevel',
            name='color',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
