# Generated by Django 2.0.9 on 2018-11-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donationlevel_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationlevel',
            options={'ordering': ['amount'], 'verbose_name': 'Spendenstufe', 'verbose_name_plural': 'Spendenstufen'},
        ),
    ]
