# Generated by Django 2.0.5 on 2018-07-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20180713_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment',
        ),
        migrations.AddField(
            model_name='donation',
            name='approval_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='donation',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.SmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
