# Generated by Django 2.0.9 on 2018-11-19 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20181101_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
