# Generated by Django 2.0.8 on 2018-09-02 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180721_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='time_start',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='time_start',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
    ]
