# Generated by Django 2.0.5 on 2018-06-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180612_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='product',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
