# Generated by Django 2.0.8 on 2018-09-08 11:21

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180907_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
    ]
