# Generated by Django 2.0.8 on 2018-09-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='section_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
