# Generated by Django 2.0.8 on 2018-09-10 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventtype_section_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='time_start',
        ),
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.TimeField(blank=True, default=datetime.time(21, 0), null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.TimeField(blank=True, default=datetime.time(19, 0), null=True),
        ),
    ]
