# Generated by Django 2.0.8 on 2018-09-10 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180910_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(blank=True, default=datetime.time(22, 0), null=True),
        ),
    ]
