# Generated by Django 2.0.9 on 2018-11-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181103_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='old_pk',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
