# Generated by Django 2.0.8 on 2018-09-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180910_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='priority',
            new_name='publish_priority',
        ),
    ]
