# Generated by Django 2.0.8 on 2018-09-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_itemtype_limited'),
        ('events', '0008_auto_20180914_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-publish_date', '-publish_priority'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
    ]
