# Generated by Django 2.0.8 on 2018-09-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180918_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item'),
        ),
    ]
