# Generated by Django 2.0.8 on 2018-09-24 11:51

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('publish_priority', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('public', models.TextField(blank=True, editable=False)),
                ('public2', models.TextField(blank=True, editable=False)),
                ('private', models.TextField(blank=True, editable=False)),
                ('references', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-publish_date', '-publish_priority'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(unique=True)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Bibliographie',
                'verbose_name_plural': 'Bibliographien',
            },
        ),
    ]
