# Generated by Django 2.0.9 on 2018-11-03 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
