# Generated by Django 2.0.5 on 2018-06-09 13:16

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.OneToOneField(default=products.models.Product.default_product, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
