# Generated by Django 2.0.8 on 2018-09-04 14:52

from django.db import migrations, models
import django.db.models.deletion
import products.behaviours


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.OneToOneField(default=products.behaviours.ProductBase._default_profile, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
