# Generated by Django 2.0.8 on 2018-09-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180918_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date', '-publish_priority'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
    ]
